resources:
  repositories:
    - repository: templates
      type: github
      endpoint: ministryofjustice
      name: ministryofjustice/staff-infrastructure-azure-landing-zone

variables:
  - group: 'github'

jobs:
- template: yaml-templates/templates/template-terraform-deploy-stage.yml@templates
  parameters:
    githubPat: $(GITHUB_PAT)
    deployFlag: true
    stageName: "Spokes"
    spokeName: "Spokes"
    environmentName: "Spokes"
    tenant_id: ${{ variables.tenant_id }}
    subscription_id: ${{ variables.subscription_id }}
    stageDisplayName: "Spokes"
    backendServiceArm: scVLZ
    backendAzureRmResourceGroupName: rg-terraform-statefiles-001
    backendAzureRmStorageAccountName: samojtfstate001
    backendAzureRmContainerName: tfstate
    backendAzureRmKey: "staff-infrastructure-azure-landing-zone-spokes.tfstate"
    yamlenv: dev_noapproval
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/spokes'