pr:
  branches:
    include:
    - main

trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: ministryofjustice
      name: ministryofjustice/staff-infrastructure-alz-templates

variables:
  - group: 'github'

stages:
- template: templates/template-terraform-deploy-stage.yml@templates
  parameters:
    terraformVersion: 1.1.4
    githubPat: $(GITHUB_PAT)
    deployFlag: true
    secureVarsFile: alz-spokes.tfvars
    stageName: "Spokes"
    spokeName: "Spokes"
    environmentName: "Spokes"
    tenant_id: ' '
    subscription_id: ' '
    stageDisplayName: "Spokes"
    backendServiceArm: scVLZ
    backendAzureRmResourceGroupName: rg-terraform-statefiles-001
    backendAzureRmStorageAccountName: samojtfstate001
    backendAzureRmContainerName: tfstate
    backendAzureRmKey: "staff-infrastructure-azure-landing-zone-spokes.tfstate"
    yamlenv: dev_noapproval
    workingDirectory: '$(System.DefaultWorkingDirectory)/staff-infrastructure-azure-landing-zone-spokes/terraform/spokes'